<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>AutoSwitcher.Cli</RootNamespace>
    <AssemblyName>AutoSwitcher</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Interop.BMDSwitcherAPI">
      <HintPath>..\..\lib\Interop.BMDSwitcherAPI.dll</HintPath>
      <EmbedInteropTypes>false</EmbedInteropTypes>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
